coverage:
  status:
    project: off
    patch: off

flags:
  unit:
    paths:
      - ".*"
    carryforward: true
  screenshot:
    paths:
      - ".*"
    carryforward: true
  integration:
    paths:
      - ".*"
    carryforward: true
