coverage:
  status:
    project: off
    patch: off

parsers:
  jacoco:
    partials_as_hits: true

flags:
  unit:
    paths:
      - ".*"
    carryforward: true
  screenshot:
    paths:
      - ".*"
    carryforward: true
  integration:
    paths:
      - ".*"
    carryforward: true
