name: Build

on:
  push:
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0.9

    - name: Download B2 binary
      run: curl https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v2.1.0/b2-linux -L -o b2
    - run: chmod +x b2

    - name: Authorize B2 account
      run: ./b2 authorize-account $B2_APPKEY_ID $B2_APPKEY
      env:
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}

    - name: Download access_token.json from B2
      run: ./b2 download-file-by-name $B2_BUCKET_NAME access_token.json access_token.json
      env:
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}

    - run: ./gradlew --no-daemon --stacktrace --console=plain check

    - name: Upload test results to codecov
      run: bash <(curl -s https://codecov.io/bash)
      if: ${{ always() }} # upload even if the build failed, in case it was just test failures
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload access_token.json to B2 (in case it was refreshed)
      run: ./b2 upload-file ${B2_BUCKET_NAME} access_token.json access_token.json
      if: ${{ always() }} # upload even if the build failed
      env:
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
