name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
    - run: chmod +x ./gradlew
    - run: ./gradlew --no-daemon --stacktrace check
      env:
        CI: true
        client_id: ${{ secrets.client_id }}
        client_secret: ${{ secrets.client_secret }}
