name: Build

on:
  push:
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ] # screenshot tests must be run on windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - run: ./gradlew --stacktrace checkLocal

      - name: Upload test results to codecov
        run: |
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
          .\codecov.exe -t ${CODECOV_TOKEN}
        if: ${{ always() }} # upload even if the build failed, in case it was just test failures
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
