name: Build

on:
  push:
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ] # screenshot tests must be run on windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '18'

      - run: ./gradlew --stacktrace checkLocal jacocoTestReportLocal

      - name: Upload mismatching screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: mismatching-screenshots
          path: src/test/resources/screenshots/**/*-MISMATCH.png
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload test results to codecov
        run: |
          Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
          .\codecov.exe -t ${CODECOV_TOKEN} -F unit
        if: ${{ always() }} # upload even if the build failed, in case it was just test failures
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
