name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0.9

    # sync the access token with B2 (ie. download it now and upload if it changes on refresh)
    - uses: jakejarvis/backblaze-b2-action@master
      env:
        SOURCE_DIR: './access_token.json'
        B2_BUCKET: ${{ secrets.B2_BUCKET_NAME }}
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}

    - run: chmod +x ./gradlew
    - run: ./gradlew --no-daemon --stacktrace check
